name: Update submodules
description: Update all submodules in this repository

runs:
  using: composite
  steps:
    - name: Update modules
      shell: bash
      env:
        MODULE: ${{ inputs.module }}
      # Update each in parallel
      # Then wait on each process id to ensure all updates are completed before moving on
      run: |
        source ./tools/REPOS.sh
        for i in ${REPOS//,/ }; do
          git submodule update --init --remote --reference "https://github.com/atsign-foundation/$i.git" -- "modules/$i" &
          pids[${i}]=$!
        done;

        for pid in ${pids[*]}; do
          wait $pid
        done;
