name: pana
description: Run pana on a local package

inputs:
  build_id:
    required: false
    description: Optional build key to use as a cache key for flutter
  path:
    required: true
    description: Path to the package to run pana on
  min_score:
    required: false
    description: Minimum score to pass
    default: '110'

runs:
  using: composite
  steps:
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: ${{ inputs.build_id != '' }}
        cache-key: ${{ inputs.build_id }}

    - name: Cache pana
      if: ${{ inputs.build_id != '' }}
      uses: actions/cache@v3
      with:
        path: ${{ runner.tool_cache }}/flutter/.pub-cache
        key: ${{ format('{0}-{1}-{2}-stable-any-pana', inputs.build_id, runner.os, runner.arch) }}
        restore-keys: ${{ format('{0}-{1}-{2}-stable-any', inputs.build_id, runner.os, runner.arch) }}

    - name: Run pana
      shell: bash
      run: |
        dart pub global activate pana
        dart pub global run pana -l 120 --no-warning --exit-code-threshold ${{ inputs.min_score }} ${{ inputs.path }}
