name: Integration Tests

on:
  workflow_dispatch:
    inputs:
      module:
        required: false
        description: The single module to update (by default all will be updated)

env:
  REPO: atsign-foundation/at_mono

jobs:
  build:
    runs-on: ubuntu-20.04

    outputs:
      commit_ref: ${{ steps.commit_id.outputs.changes_detected && steps.commit_id.outputs.commit_hash || github.sha }}
      build_id: ${{ format("{0}-{1}", github.run_id, github.run_attempt) }}

    if: ${{ github.repository != env.REPO }}
    steps:
      - uses: actions/checkout@v3

      - name: Update all modules
        if: ${{ github.event.inputs.module == "" }}
        uses: ./.github/composite/update-submodules

      - name: Update single module
        if: ${{ github.event.inputs.module != "" }}
        uses: ./.github/composite/update-submodule
        with:
          module: ${{ github.event.inputs.module }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: commit_id
        with:
          commit_message: Update submodules
          create_branch: false
          branch: trunk

      - run: echo ${{ steps.commit_id.outputs.commit_hash }}

  at_server_tests:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.build.outputs.commit_ref }}

      - uses: ./.github/composite/melos-bootstrap
        with:
          build_id: ${{ needs.build.outputs.build_id }}

      - name: "TODO: IMPLEMENT TESTS"
        run: echo "IMPLEMENT TESTS"
